<!-- 

Copyright (C) 2011 MassiveLogicSystem Development Team

This file is part of Aylin.

Aylin is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Aylin is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Aylin.  If not, see <http://www.gnu.org/licenses/>.

-->

<div id="view-content">


<div class="ui-widget-content ae-content">

	<!-- breadcrumb -->
	<div class="ui-widget-header ae-content-head">
	<span class="ae-padding-left"><?php echo $this->translate("Installation"); ?></span>
	</div>

	<!-- head -->
	<div class="ui-widget-header ae-content-head-sub">
	<div class="ae-display-inline-block ae-padding-top-bottom">
		<div class="ae-padding-left-right ae-float-left">
			<img src="<?php echo $this->baseUrl('css/common/img/setting.png') ?>" alt="" />	
		</div>
		<div class="ae-float-left">
			<span class="ae-display-block ae-font-max"><?php echo $this->translate("Setup enviroment"); ?></span>
			<span class="ae-font-normal"> <?php echo $this->translate("This module will help you configure the environment"); ?> </span>
		</div>
	</div>
	</div>
	
	<!-- content -->
	<div class="ae-display-inline-block" style="padding: 10px; width: 100%;">
		<div class="ae-content-steps">
			<div class="ui-widget-content ae-content-block">
				<span class="ae-font-title"><?php echo $this->translate("Steps"); ?>:</span>
				
				<div class="ae-content-block-data">
	
					<?php foreach($this->stepsList as $index => $step ): ?>

					<?php if ( $index == $this->currentStep ) { ?> 
						<div class="ui-priority-primary"><?php echo $this->translate($step); ?></div>
					<?php } else { ?>
						<div class="ui-priority-secondary"><?php echo $this->translate($step); ?></div>
					<?php } ?>
						
					<?php endforeach; ?>  
	
				</div>
			
			</div>
		</div>
		
		<div class="ae-context-block-separator">&nbsp;</div>
		<div class="ui-widget-content ae-content-block ae-content-data">
		
			<div class="ae-content-block-data">jasji</div>
		
		</div>
		
		<div class="ae-context-block-separator">&nbsp;</div>
		<div class="ae-content-buttons">
		
			<div class="ui-widget-content ae-content-block" style="margin-bottom: 8px;">
			<div class="ae-content-block-data">jasji</div>
			</div>

			<div class="ui-widget-content ae-content-block">
			<div class="ae-content-block-data">jasji</div>
			</div>
			
		</div>
	</div>
	
</div>





</div>